import Vue from 'vue'

import {
  ActionSheet,
  Button,
  Cell,
  CellGroup,
  DatetimePicker,
  Dialog,
  Divider,
  Field,
  Form,
  Grid,
  GridItem,
  Icon,
  Image,
  List,
  NavBar,
  Popup,
  PullRefresh,
  Search,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Toast,
  Uploader,
  DropdownMenu,
  DropdownItem,
  Circle,
  IndexBar,
  IndexAnchor,
  GoodsAction,
  GoodsActionButton,
  GoodsActionIcon,
  Loading,
  Tag
} from 'vant'

Vue.use(Button)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(Toast)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Icon)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Popup)
Vue.use(DatetimePicker)
Vue.use(Uploader)
Vue.use(Dialog)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(Divider)
Vue.use(ActionSheet)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Search)
Vue.use(Image)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Circle)
Vue.use(IndexBar)
Vue.use(IndexAnchor)
Vue.use(GoodsAction)
Vue.use(GoodsActionButton)
Vue.use(GoodsActionIcon)
Vue.use(Loading)
Vue.use(Tag)
